development: &default
  adapter: postgresql
  database: jellyfish_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  adapter:  postgresql
  database: jellyfish_development

test:
  <<: *default
  database: jellyfish_test

production:
  <<: *default
  database: jellyfish_production

docker:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db
